- name: envoy
  image: envoyproxy/envoy:v1.16-latest
  imagePullPolicy: IfNotPresent
  command:
    - "/usr/local/bin/envoy"
  args:
    - "--config-path /etc/envoy/envoy.yaml"
  resources:
    limits:
      cpu: 20m
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 64Mi
  ports:
    - containerPort: 6379
      name: envoy-redis
    - containerPort: 10001
      name: envoy-admin
    - containerPort: 10000
      name: envoy-grpc
  volumeMounts:
    - name: envoy
      mountPath: /etc/envoy
volumes:
- name: envoy
  configMap:
    name: envoy-config-servicebroker
- name: config
  hostPath:
    path: /var/lib/aion/default/config
